
package sungardhe.workflow.ws.wsdl._1;

import jakarta.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ValidationFault", targetNamespace = "urn:sungardhe:workflow:ws:messages:1.1")
public class ValidationFault
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private sungardhe.workflow.ws.messages._1.ValidationFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ValidationFault(String message, sungardhe.workflow.ws.messages._1.ValidationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ValidationFault(String message, sungardhe.workflow.ws.messages._1.ValidationFault faultInfo,
            Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *         returns fault bean: sungardhe.workflow.ws.messages._1.ValidationFault
     */
    public sungardhe.workflow.ws.messages._1.ValidationFault getFaultInfo() {
        return faultInfo;
    }

}
